package(default_visibility = ["//visibility:public"])

load("@bazel_skylib//lib:selects.bzl", "selects")

filegroup(
    name = "smhasher_postfix",
    srcs = ["smhasher_postfix.sh"],
    visibility = ["//visibility:public"],
)
