package(default_visibility = ["//visibility:public"])

cc_binary(
    name = "example",
    srcs = ["main.cc"],
    deps = [],
)

cc_binary(
    name = "check_glibc_version",
    srcs = ["check_glibc_version.cc"],
    deps = [],
)
